package org.ems.domain;
// Generated 7 May, 2017 5:12:11 PM by Hibernate Tools 3.2.2.GA


import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;


/**
 * Groupaccess generated by hbm2java
 */
@Entity
@Table(name="groupaccess"
    ,catalog="ems"
)

public class Groupaccess
 {


     private GroupaccessId id;
     private Screen screen;
     private Groupmaster groupmaster;
     private Character viewaccess;
     private Character editaccess;
     private Character deleteaccess;
     private String createdusercode;
     private Date createddate;
     private String modusercode;
     private Date moddate;

    public Groupaccess() {
    }

	
    public Groupaccess(GroupaccessId id, Screen screen, Groupmaster groupmaster, String createdusercode, Date createddate, String modusercode, Date moddate) {
        this.id = id;
        this.screen = screen;
        this.groupmaster = groupmaster;
        this.createdusercode = createdusercode;
        this.createddate = createddate;
        this.modusercode = modusercode;
        this.moddate = moddate;
    }
    public Groupaccess(GroupaccessId id, Screen screen, Groupmaster groupmaster, Character viewaccess, Character editaccess, Character deleteaccess, String createdusercode, Date createddate, String modusercode, Date moddate) {
       this.id = id;
       this.screen = screen;
       this.groupmaster = groupmaster;
       this.viewaccess = viewaccess;
       this.editaccess = editaccess;
       this.deleteaccess = deleteaccess;
       this.createdusercode = createdusercode;
       this.createddate = createddate;
       this.modusercode = modusercode;
       this.moddate = moddate;
    }
   
     @EmbeddedId
    
    @AttributeOverrides( {
        @AttributeOverride(name="organizationid", column=@Column(name="organizationid", nullable=false, length=50) ), 
        @AttributeOverride(name="groupcode", column=@Column(name="groupcode", nullable=false, length=50) ) } )
    public GroupaccessId getId() {
        return this.id;
    }
    
    public void setId(GroupaccessId id) {
        this.id = id;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumns( { 
        @JoinColumn(name="organizationid", referencedColumnName="organizationid", nullable=false, insertable=false, updatable=false), 
        @JoinColumn(name="screenno", referencedColumnName="screenno", nullable=false, insertable=false, updatable=false) } )
    public Screen getScreen() {
        return this.screen;
    }
    
    public void setScreen(Screen screen) {
        this.screen = screen;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumns( { 
        @JoinColumn(name="organizationid", referencedColumnName="organizationid", nullable=false, insertable=false, updatable=false), 
        @JoinColumn(name="groupcode", referencedColumnName="groupcode", nullable=false, insertable=false, updatable=false) } )
    public Groupmaster getGroupmaster() {
        return this.groupmaster;
    }
    
    public void setGroupmaster(Groupmaster groupmaster) {
        this.groupmaster = groupmaster;
    }
    
    @Column(name="viewaccess", length=1)
    public Character getViewaccess() {
        return this.viewaccess;
    }
    
    public void setViewaccess(Character viewaccess) {
        this.viewaccess = viewaccess;
    }
    
    @Column(name="editaccess", length=1)
    public Character getEditaccess() {
        return this.editaccess;
    }
    
    public void setEditaccess(Character editaccess) {
        this.editaccess = editaccess;
    }
    
    @Column(name="deleteaccess", length=1)
    public Character getDeleteaccess() {
        return this.deleteaccess;
    }
    
    public void setDeleteaccess(Character deleteaccess) {
        this.deleteaccess = deleteaccess;
    }
    
    @Column(name="createdusercode", nullable=false, length=50)
    public String getCreatedusercode() {
        return this.createdusercode;
    }
    
    public void setCreatedusercode(String createdusercode) {
        this.createdusercode = createdusercode;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="createddate", nullable=false, length=10)
    public Date getCreateddate() {
        return this.createddate;
    }
    
    public void setCreateddate(Date createddate) {
        this.createddate = createddate;
    }
    
    @Column(name="modusercode", nullable=false, length=50)
    public String getModusercode() {
        return this.modusercode;
    }
    
    public void setModusercode(String modusercode) {
        this.modusercode = modusercode;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="moddate", nullable=false, length=10)
    public Date getModdate() {
        return this.moddate;
    }
    
    public void setModdate(Date moddate) {
        this.moddate = moddate;
    }




}


