package org.ems.domain;
// Generated 7 May, 2017 5:12:11 PM by Hibernate Tools 3.2.2.GA


import javax.persistence.Column;
import javax.persistence.Embeddable;


/**
 * GroupaccessId generated by hbm2java
 */
@Embeddable

public class GroupaccessId
 {


     private String organizationid;
     private String groupcode;

    public GroupaccessId() {
    }

    public GroupaccessId(String organizationid, String groupcode) {
       this.organizationid = organizationid;
       this.groupcode = groupcode;
    }
   

    @Column(name="organizationid", nullable=false, length=50)
    public String getOrganizationid() {
        return this.organizationid;
    }
    
    public void setOrganizationid(String organizationid) {
        this.organizationid = organizationid;
    }

    @Column(name="groupcode", nullable=false, length=50)
    public String getGroupcode() {
        return this.groupcode;
    }
    
    public void setGroupcode(String groupcode) {
        this.groupcode = groupcode;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof GroupaccessId) ) return false;
		 GroupaccessId castOther = ( GroupaccessId ) other; 
         
		 return ( (this.getOrganizationid()==castOther.getOrganizationid()) || ( this.getOrganizationid()!=null && castOther.getOrganizationid()!=null && this.getOrganizationid().equals(castOther.getOrganizationid()) ) )
 && ( (this.getGroupcode()==castOther.getGroupcode()) || ( this.getGroupcode()!=null && castOther.getGroupcode()!=null && this.getGroupcode().equals(castOther.getGroupcode()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getOrganizationid() == null ? 0 : this.getOrganizationid().hashCode() );
         result = 37 * result + ( getGroupcode() == null ? 0 : this.getGroupcode().hashCode() );
         return result;
   }   


}


