package org.ems.domain;
// Generated 7 May, 2017 5:12:11 PM by Hibernate Tools 3.2.2.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;


/**
 * Organization generated by hbm2java
 */
@Entity
@Table(name="organization"
    ,catalog="ems"
)

public class Organization
 {


     private String organizationid;
     private String organizationname;
     private Set<Userhierlevel> userhierlevels = new HashSet<Userhierlevel>(0);
     private Set<Screen> screens = new HashSet<Screen>(0);
     private Set<Leavetype> leavetypes = new HashSet<Leavetype>(0);
     private Set<Organizationdetails> organizationdetailses = new HashSet<Organizationdetails>(0);
     private Set<Groupmaster> groupmasters = new HashSet<Groupmaster>(0);

    public Organization() {
    }

	
    public Organization(String organizationid, String organizationname) {
        this.organizationid = organizationid;
        this.organizationname = organizationname;
    }
    public Organization(String organizationid, String organizationname, Set<Userhierlevel> userhierlevels, Set<Screen> screens, Set<Leavetype> leavetypes, Set<Organizationdetails> organizationdetailses, Set<Groupmaster> groupmasters) {
       this.organizationid = organizationid;
       this.organizationname = organizationname;
       this.userhierlevels = userhierlevels;
       this.screens = screens;
       this.leavetypes = leavetypes;
       this.organizationdetailses = organizationdetailses;
       this.groupmasters = groupmasters;
    }
   
     @Id 
    
    @Column(name="organizationid", unique=true, nullable=false, length=50)
    public String getOrganizationid() {
        return this.organizationid;
    }
    
    public void setOrganizationid(String organizationid) {
        this.organizationid = organizationid;
    }
    
    @Column(name="organizationname", nullable=false, length=50)
    public String getOrganizationname() {
        return this.organizationname;
    }
    
    public void setOrganizationname(String organizationname) {
        this.organizationname = organizationname;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="organization")
    public Set<Userhierlevel> getUserhierlevels() {
        return this.userhierlevels;
    }
    
    public void setUserhierlevels(Set<Userhierlevel> userhierlevels) {
        this.userhierlevels = userhierlevels;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="organization")
    public Set<Screen> getScreens() {
        return this.screens;
    }
    
    public void setScreens(Set<Screen> screens) {
        this.screens = screens;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="organization")
    public Set<Leavetype> getLeavetypes() {
        return this.leavetypes;
    }
    
    public void setLeavetypes(Set<Leavetype> leavetypes) {
        this.leavetypes = leavetypes;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="organization")
    public Set<Organizationdetails> getOrganizationdetailses() {
        return this.organizationdetailses;
    }
    
    public void setOrganizationdetailses(Set<Organizationdetails> organizationdetailses) {
        this.organizationdetailses = organizationdetailses;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="organization")
    public Set<Groupmaster> getGroupmasters() {
        return this.groupmasters;
    }
    
    public void setGroupmasters(Set<Groupmaster> groupmasters) {
        this.groupmasters = groupmasters;
    }




}


