package org.ems.domain;
// Generated 7 May, 2017 5:12:11 PM by Hibernate Tools 3.2.2.GA


import javax.persistence.Column;
import javax.persistence.Embeddable;


/**
 * UserhiervalueId generated by hbm2java
 */
@Embeddable

public class UserhiervalueId
 {


     private String organizationid;
     private String usrValcode;

    public UserhiervalueId() {
    }

    public UserhiervalueId(String organizationid, String usrValcode) {
       this.organizationid = organizationid;
       this.usrValcode = usrValcode;
    }
   

    @Column(name="organizationid", nullable=false, length=50)
    public String getOrganizationid() {
        return this.organizationid;
    }
    
    public void setOrganizationid(String organizationid) {
        this.organizationid = organizationid;
    }

    @Column(name="usrValcode", nullable=false, length=50)
    public String getUsrValcode() {
        return this.usrValcode;
    }
    
    public void setUsrValcode(String usrValcode) {
        this.usrValcode = usrValcode;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof UserhiervalueId) ) return false;
		 UserhiervalueId castOther = ( UserhiervalueId ) other; 
         
		 return ( (this.getOrganizationid()==castOther.getOrganizationid()) || ( this.getOrganizationid()!=null && castOther.getOrganizationid()!=null && this.getOrganizationid().equals(castOther.getOrganizationid()) ) )
 && ( (this.getUsrValcode()==castOther.getUsrValcode()) || ( this.getUsrValcode()!=null && castOther.getUsrValcode()!=null && this.getUsrValcode().equals(castOther.getUsrValcode()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getOrganizationid() == null ? 0 : this.getOrganizationid().hashCode() );
         result = 37 * result + ( getUsrValcode() == null ? 0 : this.getUsrValcode().hashCode() );
         return result;
   }   


}


