package org.ems.domain;
// Generated 7 May, 2017 5:12:11 PM by Hibernate Tools 3.2.2.GA


import javax.persistence.Column;
import javax.persistence.Embeddable;


/**
 * UsergroupId generated by hbm2java
 */
@Embeddable

public class UsergroupId
 {


     private String organizationid;
     private String userCode;

    public UsergroupId() {
    }

    public UsergroupId(String organizationid, String userCode) {
       this.organizationid = organizationid;
       this.userCode = userCode;
    }
   

    @Column(name="organizationid", nullable=false, length=50)
    public String getOrganizationid() {
        return this.organizationid;
    }
    
    public void setOrganizationid(String organizationid) {
        this.organizationid = organizationid;
    }

    @Column(name="userCode", nullable=false, length=50)
    public String getUserCode() {
        return this.userCode;
    }
    
    public void setUserCode(String userCode) {
        this.userCode = userCode;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof UsergroupId) ) return false;
		 UsergroupId castOther = ( UsergroupId ) other; 
         
		 return ( (this.getOrganizationid()==castOther.getOrganizationid()) || ( this.getOrganizationid()!=null && castOther.getOrganizationid()!=null && this.getOrganizationid().equals(castOther.getOrganizationid()) ) )
 && ( (this.getUserCode()==castOther.getUserCode()) || ( this.getUserCode()!=null && castOther.getUserCode()!=null && this.getUserCode().equals(castOther.getUserCode()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getOrganizationid() == null ? 0 : this.getOrganizationid().hashCode() );
         result = 37 * result + ( getUserCode() == null ? 0 : this.getUserCode().hashCode() );
         return result;
   }   


}


