package org.ems.domain;
// Generated 21 May, 2017 10:47:02 AM by Hibernate Tools 3.2.2.GA


import java.io.Serializable;

import javax.persistence.Column;
import javax.persistence.Embeddable;


/**
 * UserprofileId generated by hbm2java
 */
@Embeddable

public class UserprofileId implements Serializable
 {


     /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private String organizationid;
     private String usercode;

    public UserprofileId() {
    }

    public UserprofileId(String organizationid, String usercode) {
       this.organizationid = organizationid;
       this.usercode = usercode;
    }
   

    @Column(name="organizationid", nullable=false, length=50)
    public String getOrganizationid() {
        return this.organizationid;
    }
    
    public void setOrganizationid(String organizationid) {
        this.organizationid = organizationid;
    }

    @Column(name="usercode", unique=true, nullable=false, length=50)
    public String getUsercode() {
        return this.usercode;
    }
    
    public void setUsercode(String usercode) {
        this.usercode = usercode;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof UserprofileId) ) return false;
		 UserprofileId castOther = ( UserprofileId ) other; 
         
		 return ( (this.getOrganizationid()==castOther.getOrganizationid()) || ( this.getOrganizationid()!=null && castOther.getOrganizationid()!=null && this.getOrganizationid().equals(castOther.getOrganizationid()) ) )
 && ( (this.getUsercode()==castOther.getUsercode()) || ( this.getUsercode()!=null && castOther.getUsercode()!=null && this.getUsercode().equals(castOther.getUsercode()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getOrganizationid() == null ? 0 : this.getOrganizationid().hashCode() );
         result = 37 * result + ( getUsercode() == null ? 0 : this.getUsercode().hashCode() );
         return result;
   }   


}


