package org.ems.domain;
// Generated 7 May, 2017 5:12:11 PM by Hibernate Tools 3.2.2.GA


import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;


/**
 * Usergroup generated by hbm2java
 */
@Entity
@Table(name="usergroup"
    ,catalog="leave_app"
)

public class Usergroup
 {


     private UsergroupId id;
     private Groupmaster groupmaster;
     private Userprofile userprofile;
     private String createdusercode;
     private Date createddate;
     private String modusercode;
     private Date moddate;

    public Usergroup() {
    }

    public Usergroup(UsergroupId id, Groupmaster groupmaster, Userprofile userprofile, String createdusercode, Date createddate, String modusercode, Date moddate) {
       this.id = id;
       this.groupmaster = groupmaster;
       this.userprofile = userprofile;
       this.createdusercode = createdusercode;
       this.createddate = createddate;
       this.modusercode = modusercode;
       this.moddate = moddate;
    }
   
     @EmbeddedId
    
    @AttributeOverrides( {
        @AttributeOverride(name="organizationid", column=@Column(name="organizationid", nullable=false, length=50) ), 
        @AttributeOverride(name="userCode", column=@Column(name="userCode", nullable=false, length=50) ) } )
    public UsergroupId getId() {
        return this.id;
    }
    
    public void setId(UsergroupId id) {
        this.id = id;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumns( { 
        @JoinColumn(name="organizationid", referencedColumnName="organizationid", nullable=false, insertable=false, updatable=false), 
        @JoinColumn(name="groupcode", referencedColumnName="groupcode", nullable=false, insertable=false, updatable=false) } )
    public Groupmaster getGroupmaster() {
        return this.groupmaster;
    }
    
    public void setGroupmaster(Groupmaster groupmaster) {
        this.groupmaster = groupmaster;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumns( { 
        @JoinColumn(name="organizationid", referencedColumnName="organizationid", nullable=false, insertable=false, updatable=false), 
        @JoinColumn(name="userCode", referencedColumnName="usercode", nullable=false, insertable=false, updatable=false) } )
    public Userprofile getUserprofile() {
        return this.userprofile;
    }
    
    public void setUserprofile(Userprofile userprofile) {
        this.userprofile = userprofile;
    }
    
    @Column(name="createdusercode", nullable=false, length=50)
    public String getCreatedusercode() {
        return this.createdusercode;
    }
    
    public void setCreatedusercode(String createdusercode) {
        this.createdusercode = createdusercode;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="createddate", nullable=false, length=10)
    public Date getCreateddate() {
        return this.createddate;
    }
    
    public void setCreateddate(Date createddate) {
        this.createddate = createddate;
    }
    
    @Column(name="modusercode", nullable=false, length=50)
    public String getModusercode() {
        return this.modusercode;
    }
    
    public void setModusercode(String modusercode) {
        this.modusercode = modusercode;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="moddate", nullable=false, length=10)
    public Date getModdate() {
        return this.moddate;
    }
    
    public void setModdate(Date moddate) {
        this.moddate = moddate;
    }




}


