package org.ems.domain;
// Generated 21 May, 2017 10:47:02 AM by Hibernate Tools 3.2.2.GA


import java.io.Serializable;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;


/**
 * Userhiervalue generated by hbm2java
 */
@Entity
@Table(name="userhiervalue"
    ,catalog="ems"
)

public class Userhiervalue implements Serializable
 {


     /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private UserhiervalueId id;
     private Userhierlevel userhierlevel;
     private String usrValDesc;
     private String parentCode;
     private String createdusercode;
     private Date createddate;
     private String modusercode;
     private Date moddate;
     private Set<Userprofile> userprofiles = new HashSet<Userprofile>(0);

    public Userhiervalue() {
    }

	
    public Userhiervalue(UserhiervalueId id, Userhierlevel userhierlevel, String usrValDesc, String parentCode, String createdusercode, Date createddate, String modusercode, Date moddate) {
        this.id = id;
        this.userhierlevel = userhierlevel;
        this.usrValDesc = usrValDesc;
        this.parentCode = parentCode;
        this.createdusercode = createdusercode;
        this.createddate = createddate;
        this.modusercode = modusercode;
        this.moddate = moddate;
    }
    public Userhiervalue(UserhiervalueId id, Userhierlevel userhierlevel, String usrValDesc, String parentCode, String createdusercode, Date createddate, String modusercode, Date moddate, Set<Userprofile> userprofiles) {
       this.id = id;
       this.userhierlevel = userhierlevel;
       this.usrValDesc = usrValDesc;
       this.parentCode = parentCode;
       this.createdusercode = createdusercode;
       this.createddate = createddate;
       this.modusercode = modusercode;
       this.moddate = moddate;
       this.userprofiles = userprofiles;
    }
   
     @EmbeddedId
    
    @AttributeOverrides( {
        @AttributeOverride(name="organizationid", column=@Column(name="organizationid", nullable=false, length=50) ), 
        @AttributeOverride(name="usrValcode", column=@Column(name="usrValcode", nullable=false, length=50) ) } )
    public UserhiervalueId getId() {
        return this.id;
    }
    
    public void setId(UserhiervalueId id) {
        this.id = id;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumns( { 
        @JoinColumn(name="organizationid", referencedColumnName="organizationid", nullable=false, insertable=false, updatable=false), 
        @JoinColumn(name="usrLvlcode", referencedColumnName="usrLvlcode", nullable=false, insertable=false, updatable=false) } )
    public Userhierlevel getUserhierlevel() {
        return this.userhierlevel;
    }
    
    public void setUserhierlevel(Userhierlevel userhierlevel) {
        this.userhierlevel = userhierlevel;
    }
    
    @Column(name="usrValDesc", nullable=false, length=50)
    public String getUsrValDesc() {
        return this.usrValDesc;
    }
    
    public void setUsrValDesc(String usrValDesc) {
        this.usrValDesc = usrValDesc;
    }
    
    @Column(name="parentCode", nullable=false, length=50)
    public String getParentCode() {
        return this.parentCode;
    }
    
    public void setParentCode(String parentCode) {
        this.parentCode = parentCode;
    }
    
    @Column(name="createdusercode", nullable=false, length=50)
    public String getCreatedusercode() {
        return this.createdusercode;
    }
    
    public void setCreatedusercode(String createdusercode) {
        this.createdusercode = createdusercode;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="createddate", nullable=false, length=10)
    public Date getCreateddate() {
        return this.createddate;
    }
    
    public void setCreateddate(Date createddate) {
        this.createddate = createddate;
    }
    
    @Column(name="modusercode", nullable=false, length=50)
    public String getModusercode() {
        return this.modusercode;
    }
    
    public void setModusercode(String modusercode) {
        this.modusercode = modusercode;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="moddate", nullable=false, length=10)
    public Date getModdate() {
        return this.moddate;
    }
    
    public void setModdate(Date moddate) {
        this.moddate = moddate;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="userhiervalue")
    public Set<Userprofile> getUserprofiles() {
        return this.userprofiles;
    }
    
    public void setUserprofiles(Set<Userprofile> userprofiles) {
        this.userprofiles = userprofiles;
    }




}


