package org.ems.domain;
// Generated 7 May, 2017 5:12:11 PM by Hibernate Tools 3.2.2.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;


/**
 * Userhierlevel generated by hbm2java
 */
@Entity
@Table(name="userhierlevel"
    ,catalog="leave_app"
)

public class Userhierlevel
 {


     private UserhierlevelId id;
     private Organization organization;
     private String usrLvlDesc;
     private String createdusercode;
     private Date createddate;
     private String modusercode;
     private Date moddate;
     private Set<Userhiervalue> userhiervalues = new HashSet<Userhiervalue>(0);

    public Userhierlevel() {
    }

	
    public Userhierlevel(UserhierlevelId id, Organization organization, String usrLvlDesc, String createdusercode, Date createddate, String modusercode, Date moddate) {
        this.id = id;
        this.organization = organization;
        this.usrLvlDesc = usrLvlDesc;
        this.createdusercode = createdusercode;
        this.createddate = createddate;
        this.modusercode = modusercode;
        this.moddate = moddate;
    }
    public Userhierlevel(UserhierlevelId id, Organization organization, String usrLvlDesc, String createdusercode, Date createddate, String modusercode, Date moddate, Set<Userhiervalue> userhiervalues) {
       this.id = id;
       this.organization = organization;
       this.usrLvlDesc = usrLvlDesc;
       this.createdusercode = createdusercode;
       this.createddate = createddate;
       this.modusercode = modusercode;
       this.moddate = moddate;
       this.userhiervalues = userhiervalues;
    }
   
     @EmbeddedId
    
    @AttributeOverrides( {
        @AttributeOverride(name="organizationid", column=@Column(name="organizationid", nullable=false, length=50) ), 
        @AttributeOverride(name="usrLvlcode", column=@Column(name="usrLvlcode", nullable=false, length=50) ) } )
    public UserhierlevelId getId() {
        return this.id;
    }
    
    public void setId(UserhierlevelId id) {
        this.id = id;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="organizationid", nullable=false, insertable=false, updatable=false)
    public Organization getOrganization() {
        return this.organization;
    }
    
    public void setOrganization(Organization organization) {
        this.organization = organization;
    }
    
    @Column(name="usrLvlDesc", nullable=false, length=50)
    public String getUsrLvlDesc() {
        return this.usrLvlDesc;
    }
    
    public void setUsrLvlDesc(String usrLvlDesc) {
        this.usrLvlDesc = usrLvlDesc;
    }
    
    @Column(name="createdusercode", nullable=false, length=50)
    public String getCreatedusercode() {
        return this.createdusercode;
    }
    
    public void setCreatedusercode(String createdusercode) {
        this.createdusercode = createdusercode;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="createddate", nullable=false, length=10)
    public Date getCreateddate() {
        return this.createddate;
    }
    
    public void setCreateddate(Date createddate) {
        this.createddate = createddate;
    }
    
    @Column(name="modusercode", nullable=false, length=50)
    public String getModusercode() {
        return this.modusercode;
    }
    
    public void setModusercode(String modusercode) {
        this.modusercode = modusercode;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="moddate", nullable=false, length=10)
    public Date getModdate() {
        return this.moddate;
    }
    
    public void setModdate(Date moddate) {
        this.moddate = moddate;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="userhierlevel")
    public Set<Userhiervalue> getUserhiervalues() {
        return this.userhiervalues;
    }
    
    public void setUserhiervalues(Set<Userhiervalue> userhiervalues) {
        this.userhiervalues = userhiervalues;
    }




}


