package org.ems.domain;
// Generated 21 May, 2017 10:47:02 AM by Hibernate Tools 3.2.2.GA


import java.io.Serializable;

import javax.persistence.Column;
import javax.persistence.Embeddable;


/**
 * UserhierlevelId generated by hbm2java
 */
@Embeddable

public class UserhierlevelId implements Serializable
 {


     /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private String organizationid;
     private String usrLvlcode;

    public UserhierlevelId() {
    }

    public UserhierlevelId(String organizationid, String usrLvlcode) {
       this.organizationid = organizationid;
       this.usrLvlcode = usrLvlcode;
    }
   

    @Column(name="organizationid", nullable=false, length=50)
    public String getOrganizationid() {
        return this.organizationid;
    }
    
    public void setOrganizationid(String organizationid) {
        this.organizationid = organizationid;
    }

    @Column(name="usrLvlcode", nullable=false, length=50)
    public String getUsrLvlcode() {
        return this.usrLvlcode;
    }
    
    public void setUsrLvlcode(String usrLvlcode) {
        this.usrLvlcode = usrLvlcode;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof UserhierlevelId) ) return false;
		 UserhierlevelId castOther = ( UserhierlevelId ) other; 
         
		 return ( (this.getOrganizationid()==castOther.getOrganizationid()) || ( this.getOrganizationid()!=null && castOther.getOrganizationid()!=null && this.getOrganizationid().equals(castOther.getOrganizationid()) ) )
 && ( (this.getUsrLvlcode()==castOther.getUsrLvlcode()) || ( this.getUsrLvlcode()!=null && castOther.getUsrLvlcode()!=null && this.getUsrLvlcode().equals(castOther.getUsrLvlcode()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getOrganizationid() == null ? 0 : this.getOrganizationid().hashCode() );
         result = 37 * result + ( getUsrLvlcode() == null ? 0 : this.getUsrLvlcode().hashCode() );
         return result;
   }   


}


