package org.ems.domain;
// Generated 21 May, 2017 10:47:02 AM by Hibernate Tools 3.2.2.GA


import java.io.Serializable;

import javax.persistence.Column;
import javax.persistence.Embeddable;


/**
 * WorkapprovaldetailsId generated by hbm2java
 */
@Embeddable

public class WorkapprovaldetailsId implements Serializable
 {


     /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private String organizationid;
     private String screenno;

    public WorkapprovaldetailsId() {
    }

    public WorkapprovaldetailsId(String organizationid, String screenno) {
       this.organizationid = organizationid;
       this.screenno = screenno;
    }
   

    @Column(name="organizationid", nullable=false, length=50)
    public String getOrganizationid() {
        return this.organizationid;
    }
    
    public void setOrganizationid(String organizationid) {
        this.organizationid = organizationid;
    }

    @Column(name="screenno", nullable=false, length=50)
    public String getScreenno() {
        return this.screenno;
    }
    
    public void setScreenno(String screenno) {
        this.screenno = screenno;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof WorkapprovaldetailsId) ) return false;
		 WorkapprovaldetailsId castOther = ( WorkapprovaldetailsId ) other; 
         
		 return ( (this.getOrganizationid()==castOther.getOrganizationid()) || ( this.getOrganizationid()!=null && castOther.getOrganizationid()!=null && this.getOrganizationid().equals(castOther.getOrganizationid()) ) )
 && ( (this.getScreenno()==castOther.getScreenno()) || ( this.getScreenno()!=null && castOther.getScreenno()!=null && this.getScreenno().equals(castOther.getScreenno()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getOrganizationid() == null ? 0 : this.getOrganizationid().hashCode() );
         result = 37 * result + ( getScreenno() == null ? 0 : this.getScreenno().hashCode() );
         return result;
   }   


}


