package org.ems.domain;
// Generated 21 May, 2017 10:47:02 AM by Hibernate Tools 3.2.2.GA


import java.io.Serializable;

import javax.persistence.Column;
import javax.persistence.Embeddable;


/**
 * WorkbasketdetailsId generated by hbm2java
 */
@Embeddable

public class WorkbasketdetailsId implements Serializable
 {


     /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private String organizationid;
     private String workassignId;

    public WorkbasketdetailsId() {
    }

    public WorkbasketdetailsId(String organizationid, String workassignId) {
       this.organizationid = organizationid;
       this.workassignId = workassignId;
    }
   

    @Column(name="organizationid", nullable=false, length=50)
    public String getOrganizationid() {
        return this.organizationid;
    }
    
    public void setOrganizationid(String organizationid) {
        this.organizationid = organizationid;
    }

    @Column(name="workassignId", nullable=false, length=50)
    public String getWorkassignId() {
        return this.workassignId;
    }
    
    public void setWorkassignId(String workassignId) {
        this.workassignId = workassignId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof WorkbasketdetailsId) ) return false;
		 WorkbasketdetailsId castOther = ( WorkbasketdetailsId ) other; 
         
		 return ( (this.getOrganizationid()==castOther.getOrganizationid()) || ( this.getOrganizationid()!=null && castOther.getOrganizationid()!=null && this.getOrganizationid().equals(castOther.getOrganizationid()) ) )
 && ( (this.getWorkassignId()==castOther.getWorkassignId()) || ( this.getWorkassignId()!=null && castOther.getWorkassignId()!=null && this.getWorkassignId().equals(castOther.getWorkassignId()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getOrganizationid() == null ? 0 : this.getOrganizationid().hashCode() );
         result = 37 * result + ( getWorkassignId() == null ? 0 : this.getWorkassignId().hashCode() );
         return result;
   }   


}


